name: Check Forbidden Filetypes

on:
  workflow_call:

jobs:
  check:
    name: Check for forbidden filetypes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run filetype check
        uses: AmsterdamUMC-test/org-security-workflows/filetype-check@main
