name: Check Forbidden Filetypes

on:
  workflow_call:
    secrets:
      TELEMETRY_URL:
        required: false
      TELEMETRY_TOKEN:
        required: false

jobs:
  filetype-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Central filetype check with telemetry
        uses: AmsterdamUMC-test/org-security-workflows/filetype-check@main
        with:
          telemetry-url: ${{ secrets.TELEMETRY_URL }}
          telemetry-token: ${{ secrets.TELEMETRY_TOKEN }}
